#!/usr/bin/env node
/**
 * Generate browser-friendly event config from config/event.json
 */
const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const configFile = path.join(rootDir, 'config', 'event.json');
const outputFile = path.join(rootDir, 'assets', 'scripts', 'event-config.js');

function buildConfig() {
  const raw = fs.readFileSync(configFile, 'utf-8');
  const data = JSON.parse(raw);

  const header = [
    '// This file is auto-generated by scripts/build-config.js',
    '// Do NOT edit directly. Update config/event.json instead.',
    ''
  ].join('\n');

  const body = `window.__EVENT_CONFIG__ = ${JSON.stringify(data, null, 2)};\n`;
  fs.writeFileSync(outputFile, `${header}${body}`, 'utf-8');
}

if (require.main === module) {
  buildConfig();
}

module.exports = buildConfig;
